apiVersion: v1
kind: Service
metadata:
  name: job-api-service
  namespace: travail-en-france
spec:
  selector:
    app: job-api-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
