apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: travail-en-france
type: Opaque
stringData:
  POSTGRES_DB: "jobsdb"
  POSTGRES_USER: "jobsuser"
  POSTGRES_PASSWORD: "change-me"
  DATABASE_URL: "postgresql://jobsuser:change-me@postgres:5432/jobsdb"
  PASSWORD_SALT: "change-this-salt"
  FLASK_SECRET_KEY: "change-this-secret"
  FT_CLIENT_ID: "replace-with-client-id"
  FT_CLIENT_SECRET: "replace-with-client-secret"
