apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: travail-en-france
spec:
  selector:
    app: web-ui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
