apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-ingestion-service
  namespace: travail-en-france
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-ingestion-service
  template:
    metadata:
      labels:
        app: job-ingestion-service
    spec:
      serviceAccountName: job-ingestion-service-sa
      containers:
        - name: job-ingestion-service
          image: job-ingestion-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
