apiVersion: v1
kind: Service
metadata:
  name: job-ingestion-service
  namespace: travail-en-france
spec:
  selector:
    app: job-ingestion-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
